### ISSUE TITLE
Resultatmelding etter SendUtvalgssak

### ISSUE THREAD

**Issue by ArveCorneliussen** [ks-no/fiks-politiskbehandling#13]
Vi må vel ha en returmelding fra møte-utvalg systemet på meldingen SendUtvalgsak fra fagsystemet? Med utvalgssak nummer, ekstern referanse etc? Det er ikke definert noen slik melding i skjemaene nå

**Comment by jarleborsheim** [comment]
Det mangler definisjon  for alle Send- schemas. Fikser alle samtidig som SendUtvalgsak.

**Comment by jarleborsheim** [comment]
Vi har laget `.kvittering` meldingstyper for alle `send` meldingstyper og `.resultat` for alle `hent` meldingstyper. 
Anser vi denne oppgaven som løst @ArveCorneliussen ?

**Comment by jarleborsheim** [comment]
Stenger oppgaven da den er løst.
