### ISSUE TITLE
Midlertidig fjerne dokumentene i tjenestene

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-politiskbehandling#18]
Hovedløpet for Fiks Politiker bør være at fagsystemet arkiverer saksfremlegg etc. og så utfører kall til tjenester i Fiks Politiker for å angi behandlingsinformasjon.

Skal dokumentene være med i kallene må det klargjøres hvordan forholdet til arkiv skal være og om tjenestene innen Fiks Politiker skal arkivere. Da må det samtidig være med informasjon tilsvarende arkivmeldingen.

Forslag: I.t.v. fjernes hoveddokument og vedlegg fra tjenestene. Felt for forslag til vedtak, vedtak etc. beholdes.
[Modellendringer for referanser.docx](https://github.com/ks-no/fiks-politiskbehandling/files/7235556/Modellendringer.for.referanser.docx)

**Comment by jarleborsheim** [comment]
Løst i [PR](https://github.com/ks-no/fiks-politiskbehandling-client-dotnet/pull/9) og stenger dermed dette issuet.
