### ISSUE TITLE
Bør behandlingsplan være måkrav?

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-politiskbehandling#21]
SendUtvalgssak uten behandlingsplan risikerer å havne i limbo.

Jeg anbefaler at det som et minimum må være en behandling i behandlingsplanen.

**Comment by jarleborsheim** [comment]
Løst i [PR](Minimum 1 Behandlingsplan i array forslagTilBehandlingsplan ks-no/fiks-politiskbehandling-client-dotnet#12) og stenger dette issuet
